### ISSUE TITLE
Can't install MFT on Intel Mac

### ISSUE THREAD

**Issue by ganning127** [apache/airavata-mft#119]
**Describe the bug**
Can't install MFT on Intel Mac

**To Reproduce**
1. Setup virtual venv 
2. pip3 install airavata-mft-cli

I've also run into this error without the venv

**Expected behavior**
MFT should install properly without error.

**Screenshots**
<img width="947" alt="Screenshot 2024-02-09 at 11 44 45 AM" src="https://github.com/apache/airavata-mft/assets/62436772/9bba0d09-ba3d-4427-9089-c9f94e8bb393">

**Additional context**
I'm using an Intel I9 Mac

**Comment by DImuthuUpe** [comment]
Can you try `pip3 install airavata-mft-cli==0.1.22` ?

**Comment by ganning127** [comment]
Resolved. I needed to downgrade my Python version to 3.10
