### ISSUE TITLE
Allow downloading a path within a resource

### ISSUE THREAD

**Issue by machristie** [apache/airavata-mft#38]
Similar to how getFileResourceMetadata can be called with a `childPath` parameter, there should be a way to specify a path when making a http download request.

**Comment by machristie** [comment]
Hi @DImuthuUpe , I realized there wasn't an issue for this so I created one.

**Comment by DImuthuUpe** [comment]
@machristie this should be fixed in https://github.com/apache/airavata-mft/commit/7c866be0a23ad49ae629d93916177a050080b9b4. There is a childResourePath field in the download api and put the relative path of the child resource or keep an empty string if you don't use that field.
