### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by spamidig** [apache/airavata-mft#83]
MacBook-Pro-405:Applications spamidig$ python3.10 -m venv venv
MacBook-Pro-405:Applications spamidig$ source venv/bin/activate
(venv) MacBook-Pro-405:Applications spamidig$ pip install airavata-mft-client
ERROR: Could not find a version that satisfies the requirement airavata-mft-client (from versions: none)
ERROR: No matching distribution found for airavata-mft-client

**Comment by DImuthuUpe** [comment]
@spamidig can you try a pip upgrade? 
python -m pip install --upgrade pip

**Comment by machristie** [comment]
@spamidig 

Try

```
pip install airavata-mft-cli
```

**Comment by spamidig** [comment]
Thanks, the cli works.
