### ISSUE TITLE
guava version issue in dependencies while adding GCS storage through CLI

### ISSUE THREAD

**Issue by praneethchityala** [apache/airavata-mft#84]
## Description

When trying add google cloud storage (GCS) buckets using standaloneServiceApplication, it shows an error as below:
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Failed to fetch file resource metadata. Timed out waiting for the response"
        debug_error_string = "{"created":"@1675112686.986866000","description":"Error received from peer 
ipv6:[::1]:7003","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Failed to fetch file resource metadata. Timed out waiting for the 
response","grpc_status":13}"
>
```

This error is because of non compatible module of guava installed from other modules, maven dependency tree is as below:

```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ mft-standalone-service ---
[INFO] org.apache.airavata:mft-standalone-service:jar:0.01-SNAPSHOT
[INFO] +- io.github.lognet:grpc-spring-boot-starter:jar:4.7.1:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.47.0:compile
[INFO] |  |  +- com.google.guava:guava:jar:31.0.1-android:compile
[INFO] |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
```

## Steps to Reproduce

- Start the 'StandaloneServiceApplication' from "airavata-mft/standalone-service/src/main/java/org.apache.airavata.mft.standalone.server/StandaloneServiceApplication"
- Then in terminal execute "mft storage add"
- Choose "Google Cloud Storage (GCS)"
- Choose "Enter Manually"
- Then provide path to the service account credential JSON

They you would be the above error.

## Expected Behavior

It should then use the credentials of GCS and show the available buckets.

## Your Environment

MAC OS, arm64e architecture.

**Comment by praneethchityala** [comment]
The error is due to an incompatible version of guava:jar:31.0.1-android which is being installed from io.grpc:grpc-netty-shaded:jar:1.47.0.

We need to install guava-31.1-jre before grpc-netty-shaded is installed to use the correct version of java.

Update the pom.xml file in location "airavata-mft/standalone-service" as below:

Add below lines in dependencies prior to any dependency:

```
<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>31.1-jre</version>
        </dependency>
```

This would resolve the issue.

**Comment by DImuthuUpe** [comment]
Thanks for the fix @praneethchityala. Reopening this because the fix should go into code. Can you please add this to https://github.com/apache/airavata-mft/blob/master/agent/pom.xml and send a pull request?

**Comment by praneethchityala** [comment]
Sure, @DImuthuUpe 
Closing the issues as PR is merged with fix.
