### ISSUE TITLE
MFT Copy command not exiting post completion of transferring files

### ISSUE THREAD

**Issue by ub0005** [apache/airavata-mft#88]
Description
MFT Copy command not exiting post completion of transferring files

Steps to reproduce:

configure source storage
configure destination storage
use the copy command to transfer files

Expected Behaviour:
The command after transferring the files should exit and allow the user to proceed with the next command.

Environment::
M2 Mac

**Comment by DImuthuUpe** [comment]
@ub0005 Can you please provide the following information

1. What is the source and destination storage type?
2. Can you paste the copy command you user?
3. Is there any error in ~/.mft/Standalone-Service-0.01/logs/airavata.log

**Comment by ub0005** [comment]
closing this issue
As I could see the MFT copy command is exiting post completion of transferring all files
